---
kind: pipeline
type: docker
name: cron_work

platform:
  os: linux
  arch: amd64

trigger:
  event:
  - cron

steps:
- name: status
  image: kayuii/github-checker
  commands:
  - URL=$(cat .version | github-checker pymumu/smartdns)
  - REQ=$(echo "$URL" | grep "Is latest" | tail -1)
  - echo "$REQ"
  - |
    if [ -z "$REQ"]; then
      github-checker pymumu/smartdns | tee .version
    else
      rm .version
    fi

- name: havenewversion
  image: alpine/git
  environment:
    SSHKEY:
      from_secret: DRONE_BUILD_KEY
    GIT_TERMINAL_PROMPT: 1
  commands:
  - |
    if [ ! -f .version ] ; then
      exit
    fi
  - git fetch --tags
  - CUR_VERSION=$(cat .version | awk '{printf $2}')
  - mkdir -p "/root/.ssh"
  - chmod 0700 /root/.ssh/
  - ssh-keyscan github.com > /root/.ssh/known_hosts
  - chmod 0600 /root/.ssh/known_hosts
  - echo "$SSHKEY" | base64 -d > /root/.ssh/id_key
  - chmod 0400 /root/.ssh/id_key
  - ssh-keygen -l -f /root/.ssh/id_key | awk '{gsub(/\(|\)/,"");print "/root/.ssh/id_" tolower($4)}' | xargs -i ln -s /root/.ssh/id_key {}
  - git add --all
  - git config --global user.name "$DRONE_COMMIT_AUTHOR"
  - git config --global user.mail "$DRONE_COMMIT_AUTHOR_EMAIL"
  - git remote set-url origin git@github.com:Kayuii/docker-smartdns.git
  - git commit -m "[drone CI] update [smartdns](https://github.com/pymumu/smartdns) to v$CUR_VERSION" --author="drone-build-bot <drone@vzxc.com>"
  - git push --set-upstream origin "$DRONE_BRANCH"
  - git tag -a "v$CUR_VERSION" -m "[drone CI] publish smartdns with webproc to v$CUR_VERSION"
  - git tag -a "Release$CUR_VERSION" -m "[drone CI] publish smartdns version to Release$XPROXY_VERSION"
  - git push origin tag "v$CUR_VERSION"
  - git push origin tag "Release$XPROXY_VERSION"

---
kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

trigger:
  ref:
  - refs/tags/v**
  - refs/tags/Release**

steps:
- name: publish
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    tags:
    - latest
    - v${DRONE_TAG##*v}
    platforms: "linux/amd64,linux/arm64,linux/arm"
    dockerfile: Dockerfile.other
    repo: kayuii/smartdns
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    ref:
    - refs/tags/v**

- name: publish-Release
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    tags:
    - ${DRONE_TAG}
    platforms: "linux/amd64,linux/arm64,linux/arm"
    dockerfile: Dockerfile.smartdns
    repo: kayuii/smartdns
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    ref:
    - refs/tags/Release**





...
