FROM golang:1.18.3-alpine as webproc

ARG WEBPROC=v0.4.0

RUN apk update && \
    apk upgrade && \
    apk add --no-cache git gcc \
	&& git clone -b $WEBPROC https://github.com/jpillora/webproc /webproc \
	&& cd /webproc \
    && VERSION=$(git describe --tags) \
    && CGO_ENABLED=0 go build -trimpath -ldflags '-X "main.version='${VERSION}'" \
    -w -s -buildid=' -o webproc .

FROM alpine:latest

COPY --from=webproc /webproc/webproc /usr/sbin/webproc

VOLUME "/opt/"

CMD ["webproc"]
